In [1]:
import requests
import json
import pandas as pd
import warnings

from pandas import DataFrame

pd.set_option("display.max_rows", None , "display.max_columns", None)
warnings.filterwarnings(action='ignore')

In [2]:
def wizely(count='1'):
    url = 'https://review-api.wiselycompany.com/api/1.0/review/elasticSearchGetReviewList.do'

    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36'
    }

    data = {
        'page': '1',
        'rgid': '1',
        'perpage': str(count),
        'keywords':'' 
    }

    resp = requests.post(url,headers=headers,data=data, verify=False).text
    jj = json.loads(resp)
    return jj

In [3]:
df = DataFrame(wizely(wizely()['Pagination']['TotalCount'])['ReviewList'])
df.head()

,RID,UNID,FullName,AgeGroup,ItemID,OrderID,RGID,Point,Contents,IsVisible,AdminUNID,Comment,Version,ProviderName,ModifiedDate,RegDate,RN,Attachments
0,36585,770532,강*인,30대,None,None,1,5,착한 가격에 최고의 품질입니다. 굳이 비싼 돈주고 다른 제품 쓸 필요가 없는 것 같...,Y,0,None,2,WISELY-2.0,NaN,1604884330407,0,[]
1,36584,752732,조*섭,50대,None,None,1,5,품질 포장 배송 모두우수하네요 굿입니다,Y,0,None,2,WISELY-2.0,NaN,1604883802050,0,[]
2,36580,767989,원*수,40대,None,None,1,5,직접 사용 해보셔요,Y,0,None,2,WISELY-2.0,NaN,1604828549637,0,[]
3,36579,235113,성*현,30대,None,None,1,4,날 면도를 한 달에 10회 미만으로 하는\n제 입장에서 와이즐리는 합리적인 소비라 ...,Y,0,None,2,WISELY-2.0,NaN,1604822059993,0,[]
4,36578,773426,김*기,40대,None,None,1,5,무게감 그립감 면도감 모두 탁월합니다~,Y,0,None,2,WISELY-2.0,NaN,1604806770493,0,[]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29923 entries, 0 to 29922
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   RID           29923 non-null  int64
 1   UNID          29923 non-null  int64
 2   FullName      29923 non-null  object
 3   AgeGroup      29923 non-null  object
 4   ItemID        0 non-null      object
 5   OrderID       0 non-null      object
 6   RGID          29923 non-null  int64
 7   Point         29923 non-null  int64
 8   Contents      29923 non-null  object
 9   IsVisible     29923 non-null  object
 10  AdminUNID     29923 non-null  int64
 11  Comment       0 non-null      object
 12  Version       29923 non-null  int64
 13  ProviderName  29923 non-null  object
 14  ModifiedDate  1005 non-null   float64
 15  RegDate       29923 non-null  int64
 16  RN            29923 non-null  int64
 17  Attachments   29923 non-null  object
dtypes: float64(1), int64(8), object(9)
memory usage: 4.1+ MB

In [5]:
df.to_csv('wizely.csv',sep=',',encoding='utf-8-sig')